import Head from "next/head";
import Header from "../components/Header";
import LotteryEntrance from "../components/LotteryEntrance";
import { useMoralis } from "react-moralis";
import Button from '@mui/material/Button';
import { Grid } from "@mui/material";

const supportedChains = ["31337", "5"];

export default function Home() {
  const { isWeb3Enabled, chainId } = useMoralis();

  return (
    <Grid
      container
      direction="column"
      alignitems="center"
      justifycontent="center">

      <Head>
        <title>DECENTRALISED LOTTERY</title>
        <meta name="description" content="Generated by Yash" />
        <link rel="icon" href="/Lottery.jpg" />
      </Head>
      <Header />
      {isWeb3Enabled ? (
        <Grid
          container
          direction="column"
          alignitems="center"
          justifycontent="center">

          {supportedChains.includes(parseInt(chainId).toString()) ? (
            <Grid
              container
              direction="column"
              alignitems="center"
              justifycontent="center">

              <LotteryEntrance />
            </Grid>
          ) : (
            <div>{`Please switch to a supported chainId. The supported Chain Ids are: ${supportedChains}`}</div>
          )}
        </Grid>
      ) : (
        <div>Please connect to a Wallet</div>
      )}
    </Grid>
  );
}

